# Generated by Django 3.2.2 on 2021-05-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('major', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=150)),
                ('gpa', models.IntegerField()),
            ],
        ),
    ]
